spring.application.name=hr-payroll

# SERVER PORT
server.port=8101

# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb02
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console-02
spring.jpa.defer-datasource-initialization=true

# Microservice URLs
hr-worker.host=http://localhost:8001