server:
  port: 8765

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
    loadbalancer:
      retry:
        enabled: true
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
