spring.application.name=hr-config-server

# Config Server port
server.port=8888


# Git repository configuration
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.uri=https://github.com/Lucas-Yohan/ms-client-service

